import {Platform, StatusBar, StyleSheet} from 'react-native';
import type {ThemeColors} from '../types';

export function createThemedStyles(colors: ThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    appShell: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      padding: 24,
      paddingBottom: 36,
    },
    topBar: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    eyebrow: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    themeToggle: {
      padding: 8,
    },
    menuIcon: {
      gap: 4,
      width: 24,
    },
    menuBar: {
      backgroundColor: colors.primary,
      height: 3,
      width: '100%',
    },
    themeToggleText: {
      display: 'none',
    },
    modalOverlay: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    modalBackdrop: {
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
      flex: 1,
    },
    settingsPanel: {
      backgroundColor: colors.background,
      borderLeftColor: colors.border,
      borderLeftWidth: 1,
      maxWidth: 360,
      padding: 22,
      paddingTop: 28,
      width: '86%',
    },
    settingsHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 26,
    },
    settingsTitle: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '900',
    },
    closeButton: {
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    closeButtonText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '800',
    },
    settingsSectionTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '900',
      marginBottom: 10,
      marginTop: 8,
    },
    optionList: {
      gap: 10,
      marginBottom: 18,
    },
    optionRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      paddingVertical: 14,
    },
    optionRowSelected: {
      borderColor: colors.primary,
      borderWidth: 2,
    },
    optionLabel: {
      color: colors.text,
      flex: 1,
      fontSize: 15,
      fontWeight: '800',
    },
    optionSelected: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '900',
      marginLeft: 12,
    },
    privacyBox: {
      backgroundColor: colors.noticeBackground,
      borderColor: colors.noticeBorder,
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 'auto',
      padding: 16,
    },
    title: {
      color: colors.text,
      fontSize: 34,
      fontWeight: '800',
      lineHeight: 40,
      marginBottom: 16,
    },
    body: {
      color: colors.mutedText,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 28,
    },
    helperText: {
      color: colors.subtleText,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 14,
    },
    featureList: {
      gap: 14,
      marginBottom: 32,
    },
    featureItem: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 15,
    },
    featureDot: {
      backgroundColor: colors.success,
      borderRadius: 6,
      height: 12,
      marginRight: 12,
      width: 12,
    },
    featureText: {
      color: colors.text,
      flex: 1,
      fontSize: 15,
      fontWeight: '700',
    },
    actionGroup: {
      gap: 12,
      marginTop: 'auto',
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 8,
      paddingHorizontal: 18,
      paddingVertical: 16,
    },
    disabledButton: {
      opacity: 0.45,
    },
    primaryButtonText: {
      color: colors.primaryText,
      fontSize: 16,
      fontWeight: '800',
    },
    secondaryButton: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 18,
      paddingVertical: 16,
    },
    secondaryButtonText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    noticeBox: {
      backgroundColor: colors.noticeBackground,
      borderColor: colors.noticeBorder,
      borderRadius: 8,
      borderWidth: 1,
      marginBottom: 28,
      padding: 16,
    },
    noticeTitle: {
      color: colors.noticeTitle,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 6,
    },
    noticeText: {
      color: colors.noticeText,
      fontSize: 15,
      lineHeight: 22,
    },
    appList: {
      gap: 12,
      marginBottom: 28,
    },
    appListSeparator: {
      height: 12,
    },
    appRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      padding: 14,
    },
    appRowSelected: {
      borderColor: colors.primary,
      borderWidth: 2,
    },
    appIcon: {
      alignItems: 'center',
      borderRadius: 8,
      height: 46,
      justifyContent: 'center',
      marginRight: 14,
      width: 46,
    },
    appIconText: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: '900',
    },
    appTextGroup: {
      flex: 1,
    },
    appName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 3,
    },
    appCategory: {
      color: colors.subtleText,
      fontSize: 13,
      fontWeight: '600',
    },
    checkmark: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '800',
    },
    metricPanel: {
      backgroundColor: colors.metricBackground,
      borderRadius: 8,
      marginBottom: 28,
      padding: 24,
    },
    metricNumber: {
      color: colors.metricText,
      fontSize: 44,
      fontWeight: '900',
      marginBottom: 4,
    },
    metricLabel: {
      color: colors.metricLabel,
      fontSize: 15,
      fontWeight: '700',
    },
    dashboardHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    headerActions: {
      flexDirection: 'row',
      gap: 18,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
    },
    linkText: {
      color: colors.primary,
      fontSize: 15,
      fontWeight: '800',
    },
    usageCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      padding: 14,
    },
    usageRowTop: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    appIconSmall: {
      alignItems: 'center',
      borderRadius: 8,
      height: 36,
      justifyContent: 'center',
      marginRight: 12,
      width: 36,
    },
    appIconTextSmall: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '900',
    },
    usageName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    usageTextGroup: {
      flex: 1,
    },
    usageStatus: {
      color: colors.subtleText,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 2,
    },
    usageTime: {
      color: colors.mutedText,
      fontSize: 15,
      fontWeight: '800',
    },
    limitControls: {
      borderTopColor: colors.border,
      borderTopWidth: 1,
      gap: 12,
      marginTop: 14,
      paddingTop: 14,
    },
    limitTextGroup: {
      gap: 3,
    },
    limitTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
    },
    limitSubtitle: {
      color: colors.subtleText,
      fontSize: 12,
      fontWeight: '700',
    },
    limitActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    limitChip: {
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    limitChipSelected: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    limitChipText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '900',
    },
    limitChipTextSelected: {
      color: colors.primaryText,
    },
    limitStepper: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
    },
    limitStepButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceAlt,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 34,
      justifyContent: 'center',
      width: 42,
    },
    limitStepText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
    },
    limitValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
      minWidth: 54,
      textAlign: 'center',
    },
  });
}
