import {StyleSheet} from 'react-native';
import type {ThemeColors} from '../types';

export function createThemedStyles(colors: ThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    appShell: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      padding: 24,
      paddingBottom: 40,
    },
    topBar: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    eyebrow: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    themeToggle: {
      padding: 8,
    },
    menuIcon: {
      gap: 5,
      width: 28,
    },
    menuBar: {
      backgroundColor: colors.primary,
      height: 2.5,
      borderRadius: 2,
      width: '100%',
    },
    modalOverlay: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    modalBackdrop: {
      backgroundColor: 'rgba(15, 23, 42, 0.6)',
      flex: 1,
    },
    settingsPanel: {
      backgroundColor: colors.background,
      borderLeftColor: colors.border,
      borderLeftWidth: 1,
      maxWidth: 360,
      padding: 24,
      paddingTop: 40,
      width: '85%',
    },
    settingsHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 32,
    },
    settingsTitle: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '800',
    },
    closeButton: {
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    closeButtonText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    settingsSectionTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
      marginBottom: 12,
      marginTop: 20,
    },
    optionList: {
      gap: 12,
      marginBottom: 24,
    },
    optionRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 18,
    },
    optionRowSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.noticeBackground,
      borderWidth: 2,
    },
    optionLabel: {
      color: colors.text,
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
    },
    optionSelected: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '800',
      marginLeft: 12,
    },
    privacyBox: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 20,
      marginTop: 'auto',
      padding: 20,
    },
    title: {
      color: colors.text,
      fontSize: 32,
      fontWeight: '800',
      lineHeight: 40,
      marginBottom: 12,
    },
    body: {
      color: colors.mutedText,
      fontSize: 16,
      lineHeight: 26,
      marginBottom: 32,
    },
    helperText: {
      color: colors.subtleText,
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 16,
    },
    featureList: {
      gap: 16,
      marginBottom: 40,
    },
    featureItem: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingHorizontal: 20,
      paddingVertical: 18,
      flexDirection: 'row',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    featureDot: {
      backgroundColor: colors.success,
      borderRadius: 8,
      height: 12,
      marginRight: 16,
      width: 12,
    },
    featureText: {
      color: colors.text,
      flex: 1,
      fontSize: 16,
      fontWeight: '600',
    },
    actionGroup: {
      gap: 16,
      marginTop: 'auto',
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingHorizontal: 24,
      paddingVertical: 18,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 4,
    },
    disabledButton: {
      opacity: 0.4,
    },
    primaryButtonText: {
      color: colors.primaryText,
      fontSize: 17,
      fontWeight: '800',
    },
    secondaryButton: {
      alignItems: 'center',
      borderRadius: 16,
      paddingHorizontal: 24,
      paddingVertical: 18,
      backgroundColor: colors.surfaceAlt,
    },
    secondaryButtonText: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
    },
    noticeBox: {
      backgroundColor: colors.noticeBackground,
      borderRadius: 20,
      marginBottom: 24,
      padding: 20,
    },
    noticeTitle: {
      color: colors.noticeTitle,
      fontSize: 17,
      fontWeight: '800',
      marginBottom: 8,
    },
    noticeText: {
      color: colors.noticeText,
      fontSize: 15,
      lineHeight: 24,
    },
    appList: {
      gap: 16,
      marginBottom: 32,
    },
    appListSeparator: {
      height: 12,
    },
    appRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 20,
      flexDirection: 'row',
      padding: 16,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    appRowSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.noticeBackground,
    },
    appIcon: {
      alignItems: 'center',
      borderRadius: 14,
      height: 52,
      justifyContent: 'center',
      marginRight: 16,
      width: 52,
    },
    appIconText: {
      color: '#FFFFFF',
      fontSize: 22,
      fontWeight: '900',
    },
    appTextGroup: {
      flex: 1,
    },
    appName: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
      marginBottom: 4,
    },
    appCategory: {
      color: colors.subtleText,
      fontSize: 13,
      fontWeight: '600',
    },
    checkmark: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '800',
    },
    metricPanel: {
      backgroundColor: colors.metricBackground,
      borderRadius: 24,
      marginBottom: 32,
      padding: 32,
      alignItems: 'center',
    },
    metricNumber: {
      color: colors.metricText,
      fontSize: 52,
      fontWeight: '900',
      marginBottom: 8,
    },
    metricLabel: {
      color: colors.metricLabel,
      fontSize: 16,
      fontWeight: '700',
    },
    dashboardHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    headerActions: {
      flexDirection: 'row',
      gap: 20,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '800',
    },
    linkText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: '700',
    },
    usageCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 18,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    usageRowTop: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    appIconSmall: {
      alignItems: 'center',
      borderRadius: 10,
      height: 40,
      justifyContent: 'center',
      marginRight: 14,
      width: 40,
    },
    appIconTextSmall: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '900',
    },
    usageName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
    },
    usageTextGroup: {
      flex: 1,
    },
    usageStatus: {
      color: colors.subtleText,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 2,
    },
    usageTime: {
      color: colors.mutedText,
      fontSize: 16,
      fontWeight: '800',
    },
    limitControls: {
      borderTopColor: colors.border,
      borderTopWidth: 1,
      gap: 16,
      marginTop: 18,
      paddingTop: 18,
    },
    limitTextGroup: {
      gap: 4,
    },
    limitTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    limitSubtitle: {
      color: colors.subtleText,
      fontSize: 13,
      fontWeight: '500',
    },
    limitActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    limitChip: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    limitChipSelected: {
      backgroundColor: colors.primary,
    },
    limitChipText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    limitChipTextSelected: {
      color: colors.primaryText,
    },
    limitStepper: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
    },
    limitStepButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 12,
      height: 44,
      justifyContent: 'center',
      width: 52,
    },
    limitStepText: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '700',
    },
    limitValue: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      minWidth: 60,
      textAlign: 'center',
    },
  });
}
